// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ' AIzaSyBY7e5tZXgNB90PjmkI1h8NmAIb5M3aH80',
    appId: '1:38193451029:android:51413bdb314d93681dfe1c',
    messagingSenderId: '38193451029',
    projectId: 'notaatapp',
    storageBucket: 'notaatapp.appspot.com'
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDYzaIYUpIOTZbJKnluc4UY7yM6pgz2Q1Q',
  //   appId: '1:186710241320:android:c74745b2509af65d76851d',
  //   messagingSenderId: '365058967814',
  //   projectId: 'yosrv-ohone-notiviction',
  //   databaseURL: 'https://catalogue-2210d.firebaseio.com',
  //   storageBucket: 'yosrv-ohone-notiviction.appspot.com',
  //   androidClientId: '186710241320-adelpjcha8tb73950mth12vvrt27ddht.apps.googleusercontent.com',
  //   iosClientId: '186710241320-adelpjcha8tb73950mth12vvrt27ddht.apps.googleusercontent.com',
  //   iosBundleId: 'com.wrteam.catalogue',
  // );
}
